config/routes.rb
Rails.application.routes.draw do
  get '/', to: "application#index"  

  post '/login', to: "application#login"
  get '/logout', to: "application#logout"

  post '/create_user', to: "application#create_user"

  post '/create_event', to: "application#create_event"
  get '/delete_event/:id', as: 'delete_event', to: "application#delete_event"

  get '/join_event/:id', as: 'join_event', to: "application#join_event"
  get '/leave_event/:id', as: 'leave_event', to: "application#leave_event"

  post '/create_comment/:id', as: 'create_comment', to: "application#create_comment"
  get '/delete_comment/:id', as: 'delete_comment', to: "application#delete_comment"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users
  has_many :users, through: :event_users

  has_many :comments

  def add_comment
  end

  def add_user(user)
    return unless user.is_a?(User)

    return if self.users.include?(user)
    self.users << user

    save
  end

  def remove_user(user)
    return unless user.is_a?(User)

    self.users.delete(user)

    save
  end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/login.rb
class Login
  include ActiveModel::Model

  attr_accessor :email, :password
end

app/models/user.rb
class User < ApplicationRecord
  ROLE_USER = 1
  ROLE_ADMIN = 2

  has_many :comments

  has_many :event_users
  has_many :events, through: :event_users

  has_secure_password

  def admin?
    role_id == ROLE_ADMIN
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_events, :set_user

  def index
    # reset_session
  end

  def load_events
    @events ||= Event.all.includes(:users).order("created_at desc")
  end

  def logout
    session[:current_user_id] = nil

    redirect_to action: 'index'
  end

  def delete_event
    redirect_to '/' unless @user && @user.admin?

    load_event

    @event.delete
    redirect_to '/' 
  end

  def create_event
    redirect_to '/' unless @user.admin?

    event = Event.new(event_params)
    if event.save
      redirect_to '/', notice: 'User was successfully created.'
    else
      format.html { render '/' }
    end
  end

  def join_event
    redirect_to '/' unless @user

    load_event

    if @event.add_user(@user)
      redirect_to '/', notice: 'Nice of you yo join!'
    else
        format.html { redirect_to '/', notice: 'Something went wrong!' }
    end
  end

  def create_comment
    redirect_to '/' unless @user

    load_event
    comment = Comment.new(comment_params)
    comment.event = @event
    comment.user = @user

    if comment.save
      redirect_to '/', notice: 'Good comment!'
    else
      format.html { redirect_to '/', notice: 'Something went wrong!' }
    end
  end

  def delete_comment
    redirect_to '/' unless @user

    load_comment

    redirect_to '/' unless @comment.user == @user

    if @comment.delete
      redirect_to '/', notice: 'Comment removed'
    else
    end
  end

  def leave_event
    redirect_to '/' unless @user

    load_event

    if @event.remove_user(@user)
      redirect_to '/', notice: 'So sad that you leave!'
    else
        format.html { redirect_to '/', notice: 'Something went wrong!' }
    end
  end

  def login
    user = User.find_by_email(login_params[:email])
    if(user && user.authenticate(login_params[:password]))
        session[:current_user_id] = user.id
        redirect_to action: 'index'
    else
        format.html { redirect_to '/', notice: 'Something went wrong!' }
    end
  end

  def create_user
    @user = User.new(user_params)

    @user.role_id = User::ROLE_USER

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to '/', notice: 'User was successfully created.' }
      else
        format.html { render '/' }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    return nil unless session[:current_user_id]
    @user = User.find(session[:current_user_id])
  end
  
  def load_event
    @event ||= Event.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def login_params
    params.require(:login).permit(:email, :password)
  end

  def event_params
    params.require(:event).permit(:name, :description, :start_at, :end_at)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def load_comment
    @comment ||= Comment.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :load_events

  def index
  end

  def load_events
    @events ||= Event.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.slim
.container
  .pricing-header.px-3.py-3.pt-md-5.pb-md-4.mx-auto.text-center
    h2 YA Trollhättan Coding Events
    p.lead Here you can join upcoming events in YA school events.
    hr
  - if @user&.admin?
      = form_with model: Event.new, local: true, url: create_event_path do |f|
        .row
          .col-lg-4
              .field
                = f.label :name
                = f.text_field :name
              .field
                = f.label :description
                = f.text_area :description
          .col-lg-4
              .field
                = f.label :start_at
                = f.text_field :start_at
              .field
                = f.label :end_at
                = f.text_field :end_at
          .col-lg-4
        .row
          .col-sm-12
              .field
                = f.submit
  .row
    .col-8
      .h3 Events
      - @events.each do |event|
        .card
          .card-body
            .row
              .col-sm-12
                h5.card-title.float-left = event.name
                p.float-right = event.start_at
            hr
            = event.description
            div
              br
              b participants
              br
              = event.users.map(&:email).join(", ")
            hr
            div
              - if @user
                .btn-group
                  - if event.users.include?(@user)
                    = link_to "Leave", leave_event_path(event.id), class: 'btn btn-warning'
                  - else
                    = link_to "Join", join_event_path(event.id), class: 'btn btn-primary'

                - if @user&.admin?
                  = link_to "Delete", delete_event_path(event.id), class: 'btn btn-danger'
                hr
                  - event.comments.each do |comment|
                    div.alert.alert-secondary 
                      .row
                        .col-sm-12
                          = comment.content
                          - if comment.user == @user
                            = link_to "Delete", delete_comment_path(comment.id), class: 'btn btn-danger btn-sm float-right'
                  = form_with model: Comment.new, local: true, url: create_comment_path(event.id) do |f|
                    = f.text_area :content, class: "form-control"
                    = f.submit "Comment", class: "btn btn-secondary"
        hr
    .col-4
      - if session[:current_user_id]
        = link_to "Logga ut", logout_path, class: "btn btn-danger btn-block"
      - else
        .h4.mb-4 Login
        = form_with model: Login.new, local: true, url: login_path do |f|
          .mb-3
            = f.label :email
            = f.text_field :email, class: "form-control"
          .mb-3
            = f.label :password
            = f.password_field :password, class: "form-control"
          .mb-3
            = f.submit 'Log in', class: 'btn btn-primary btn-block'
        hr
        h4.mb-4 Sign up
        = form_with model: User.new, local: true, url: create_user_path do |f|
          .mb-3
            = f.label :email
            = f.text_field :email, class: "form-control"
          .mb-3
            = f.label :password
            = f.password_field :password, class: "form-control"
          .field
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: "form-control"
          .field
            = f.submit 'Sign up', class: 'btn btn-primary btn-block'
.footer
  p This app runs on:
  p = "Ruby #{RUBY_VERSION}, Rails #{Rails::VERSION::STRING}"

app/views/events/index.slim
html
  head
  body
    .container
      .row
        .col-6
          .h3 Events
          - @events.each do |event|
            = event.name
        .col-6
          .h3 Login
          = form_with model: User.new, local: true do |f|
            .field
              = f.label :email
              = f.text_field :email
            .field
              = f.label :password
              = f.password_field :password
            .field
              = f.label :password_confirmation
              = f.password_field :password_confirmation

app/views/layouts/application.slim
html
  head
    title App
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body.bg-light
    = yield

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>